plugins { id 'com.android.application' }
android {
    namespace 'dev.duofold'
    compileSdk 36
    useLibrary 'android.test.runner'
    useLibrary 'android.test.base'
    defaultConfig {
        applicationId 'dev.duofold'
        minSdk 29
        targetSdk 36
        versionCode 7
        versionName '0.6.0'
        testInstrumentationRunner 'android.test.InstrumentationTestRunner'
    }
    flavorDimensions 'api'
    productFlavors {
        compat {
            dimension 'api'
            minSdk 29
        }
        standard {
            dimension 'api'
            minSdk 34
        }
    }
    buildFeatures { aidl true; buildConfig true }
    testOptions { unitTests.returnDefaultValues = true }
    compileOptions { sourceCompatibility JavaVersion.VERSION_17; targetCompatibility JavaVersion.VERSION_17 }
    buildTypes { release { minifyEnabled false } }
}
dependencies {
    implementation project(':motion')
    implementation 'dev.rikka.shizuku:api:13.1.5'
    implementation 'dev.rikka.shizuku:provider:13.1.5'
    implementation 'androidx.annotation:annotation:1.9.1'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'junit:junit:4.13.2'
}
